### ISSUE TITLE
builds are broken

### ISSUE THREAD

**Issue by lukepighetti** [medama-io/medama#18]
Hey there! Was super curious to try this out but it looks like builds are broken

1. core taskfile isn't linked to main taskfile
2. `cd core && task build` fails

```
% task build  
task: [generate] go generate ./...
INFO    convenient      Convenient errors are disabled, skip reduce
sed: 1: "api/oas_request_decoder ...": command a expects \ followed by text
generate.go:7: running "./generate.sh": exit status 1
exit status 1
```

Any insights? Is it an environment issue on my end?

**Comment by ayuhito** [comment]
https://github.com/medama-io/medama/commit/9379911b35b1d7e8ea96837bc83a9bdc32b1ef5f should fix it. Seems like it was just a weird gimmick related to `sed` running differently between macOS and Linux. Let me know if you have any issues building or the fix was unrelated!

For quick testing locally, you can run `task dev -- start` to run a development build locally in `/core`. You can then run `pnpm dev` in `/dashboard` and you should have a local development build running. I'll try to get some simple documentation up eventually to help anyone who wants to build from source until I'm happy to go for a proper release.

**Comment by ayuhito** [comment]
#20 should resolve this in the meantime. This [Dockerfile](https://github.com/medama-io/medama/blob/main/Dockerfile) shows how to build the whole project from source, so you can trace how that works or simply run the Docker image itself! I've got it deploying automatically to `fly.io` so it's functionally working. 

Onto cleaning up the dashboard (backend is pretty much ready) and we'll have a proper end-user release soon 🎉

**Comment by ayuhito** [comment]
Hi @lukepighetti, I've gone ahead and cut the first real release [v0.1.0](https://github.com/medama-io/medama/releases/tag/v0.1.0) to GitHub. Feel free to check out the [README](https://github.com/medama-io/medama) and [documentation](https://oss.medama.io/introduction) for more details.

Would love to hear any feedback or issues experienced when it comes to spinning up an analytics instance. Self-hostability is a huge focus for this project so if there are any ways to make it easier, I want to find a way to do that.

Still lots of things to work on, but I think this is very usable for early adopters 👍
