### ISSUE TITLE
question about time selection  

### ISSUE THREAD

**Issue by rolikeusch** [medama-io/medama#88]
it‘s not a bug report, it‘s more a question of understanding.
if i select the timeframe `All Time` it shows only data until June 30 (until end of last month), should it not show all data until today? same goes with `Previous Year` and `Previous half year`.

**Comment by ayuhito** [comment]
That was done intentionally since data from the current month is incomplete, but maybe in practice it's not very useful to omit such data? It does feel a little unexpected for the end user.

What are your thoughts on this? Do you think that default behaviour should be changed?

**Comment by rolikeusch** [comment]
not sure what other think, but for me it‘s more logical that it shows the data until the actual day.

**Comment by ayuhito** [comment]
I've gone ahead and pushed a fix that updates the chart tooltips to be a little clearer on what range of data is covered. e.g. instead of `June 30` it would be `Week of June 30` which hopefully makes sense. There was also an additional bug related to querying data split up into intervals of 1 month which has now been fixed.

You can check out the changes on the demo: https://demo.medama.io/fontsource.org

I'll probably release a new version with these fixes tomorrow or the day after.
